version: '2.2'

#networks:
#  outside:
#    external: true
    
services:
  tor-socks-proxy:
    container_name: tor-socks-proxy
    image: peterdavehello/tor-socks-proxy:latest
    #build: tor-socks-proxy
    ports:
      - "127.0.0.1:53:53/udp"
      - "127.0.0.1:9150:9150/tcp"
    restart: unless-stopped
          
  # Manticore Search is a small yet powerful database for search with awesome full-text search capabilities
  manticore:
    # we'll just use their official image
    image: manticoresearch/manticore:3.4.0
    # and create a volume for data persistency
    volumes:
      - ./data:/var/lib/manticore
    ports:
      - 9306:9306
            
  # python script
  #python:
  #  build: python
  #  networks: 
  #    - outside
  #  depends_on: 
  #    - manticore
  #    #- tor-socks-proxy
  #  command: python ./generic_crawler.py
    
  # let's also add a tiny php script to visualize what we have in Manticore
  web:
    # we'll use php 7.2. + Apache for that
    image: php:7.2-apache
    # it also depends on Manticore
    depends_on:
      - manticore
    # let's bind it to 8082 port locally
    ports:
      - 8082:80
    # we'll mirror folder "www" to /var/www/html/ inside the web server container so ./www/index.php will be the front page
    volumes:
      - ./www/:/var/www/html/
